apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  selector:
    app: wisecow
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001  # Optional: you can specify a port, or let Kubernetes choose it
  type: NodePort

